import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  notesSidebar: [
    'intro',
    {
      type: 'category',
      label: '基础认知',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'foundations'}],
    },
    {
      type: 'category',
      label: 'Serving 与推理',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'serving'}],
    },
    {
      type: 'category',
      label: '观测与治理',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'observability'}],
    },
    {
      type: 'category',
      label: '使用指南',
      collapsible: true,
      collapsed: false,
      items: ['guides/development', 'guides/deployment'],
    },
  ],
};

export default sidebars;
